### PR TITLE
Initial work on running in Docker

### PR DESCRIPTION
**Pull request by andrew-d**
I don't know Docker that well, but this seems to work?

### CODE REVIEW

**Comment by arubdesu** [comment]
Pardon that I'm a bit backlogged to test this locally, but I had a much more learned (and opinionated) friend take a look and he gave the Dockerfile a 👍
(Thanks, @groob)

**Comment by groob** [comment]
One thing that can be improved is checking for the default postgres environment variables. 

When two containers are linked, the environment variables inherit the link name, so if I link 
`--link some-postgres:postgres`, the vars will actually look like this inside the linked container.

```
HOSTNAME=e0cc717f5039
SHLVL=0
HOME=/root
PG_VERSION=9.5.3-1.pgdg80+1
POSTGRES_ENV_PG_VERSION=9.5.3-1.pgdg80+1
POSTGRES_ENV_LANG=en_US.utf8
TERM=xterm
PATH=/usr/lib/postgresql/9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
POSTGRES_ENV_POSTGRES_PASSWORD=mysecretpassword
POSTGRES_ENV_GOSU_VERSION=1.7
POSTGRES_PORT_5432_TCP_ADDR=172.17.0.4
POSTGRES_PORT_5432_TCP_PORT=5432
LANG=en_US.utf8
POSTGRES_PORT_5432_TCP_PROTO=tcp
POSTGRES_PORT=tcp://172.17.0.4:5432
PG_MAJOR=9.5
POSTGRES_ENV_PG_MAJOR=9.5
GOSU_VERSION=1.7
PWD=/
POSTGRES_NAME=/mad_hawking/postgres
POSTGRES_PORT_5432_TCP=tcp://172.17.0.4:5432
PGDATA=/var/lib/postgresql/data
POSTGRES_ENV_PGDATA=/var/lib/postgresql/data
```

**Comment by mwielgoszewski** [comment]
@andrew-d is there anymore work to be done on this?

**Comment by andrew-d** [comment]
Just rebased and force-pushed; this should be good to go.

**Pull request merged**
